import { ProductVariant } from './types';

const tShirt: ProductVariant[] = [
  {
    name: 'Tumio Hete Dakho',
    price: 399,
    image: '/images/products/t-shirts/tumio-hete-dakho/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',  image: '/images/products/t-shirts/tumio-hete-dakho/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',        image: '/images/products/t-shirts/tumio-hete-dakho/white.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow',image: '/images/products/t-shirts/tumio-hete-dakho/bright-yellow.jpeg' },
      { hex: '#54575c', name: 'Grey',         image: '/images/products/t-shirts/tumio-hete-dakho/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',        image: '/images/products/t-shirts/tumio-hete-dakho/black.jpeg'         },
      { hex: '#384b38', name: 'Olive Green',  image: '/images/products/t-shirts/tumio-hete-dakho/olive-green.jpeg'   },
      { hex: '#202157', name: 'Midnight Blue',image: '/images/products/t-shirts/tumio-hete-dakho/midnight-blue.jpeg' },
    ],
  },
  {
    name: 'Pahad Calling',
    price: 399,
    image: '/images/products/t-shirts/pahad-calling/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/pahad-calling/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/pahad-calling/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/pahad-calling/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/pahad-calling/black.jpeg'         },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/pahad-calling/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/pahad-calling/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Hebby Lyadh Lagche',
    price: 399,
    image: '/images/products/t-shirts/hebby-lyadh-lagche/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/hebby-lyadh-lagche/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/hebby-lyadh-lagche/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/hebby-lyadh-lagche/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/hebby-lyadh-lagche/black.jpeg'         },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/hebby-lyadh-lagche/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/hebby-lyadh-lagche/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Kolkata: The City of Joy',
    price: 399,
    image: '/images/products/t-shirts/kolkata-the-city-of-joy/red.jpeg',
    colors: [
      { hex: '#cc2200', name: 'Red',           image: '/images/products/t-shirts/kolkata-the-city-of-joy/red.jpeg'           },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/kolkata-the-city-of-joy/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/kolkata-the-city-of-joy/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/kolkata-the-city-of-joy/black.jpeg'         },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/kolkata-the-city-of-joy/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/kolkata-the-city-of-joy/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Nijer Chorkae Tel Dao',
    price: 399,
    image: '/images/products/t-shirts/nijer-chorkae-tel-dao/black.jpeg',
    colors: [
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/nijer-chorkae-tel-dao/black.jpeg'        },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/nijer-chorkae-tel-dao/white.jpeg'        },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/nijer-chorkae-tel-dao/grey.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/nijer-chorkae-tel-dao/bright-yellow.jpeg'},
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/nijer-chorkae-tel-dao/olive-green.jpeg'  },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/nijer-chorkae-tel-dao/metallic-blue.jpeg'},
    ],
  },
  {
    name: 'Taka Mati, Mati Taka',
    price: 399,
    image: '/images/products/t-shirts/taka-mati-mati-taka/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/taka-mati-mati-taka/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/taka-mati-mati-taka/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/taka-mati-mati-taka/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/taka-mati-mati-taka/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/taka-mati-mati-taka/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/taka-mati-mati-taka/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/taka-mati-mati-taka/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Dugga Dugga',
    price: 399,
    image: '/images/products/t-shirts/dugga-dugga/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/dugga-dugga/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/dugga-dugga/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/dugga-dugga/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/dugga-dugga/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/dugga-dugga/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/dugga-dugga/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/dugga-dugga/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Bandorer Bandrami',
    price: 399,
    image: '/images/products/t-shirts/bandorer-bandrami/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/bandorer-bandrami/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/bandorer-bandrami/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/bandorer-bandrami/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/bandorer-bandrami/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/bandorer-bandrami/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/bandorer-bandrami/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/bandorer-bandrami/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Berolei Khorcha',
    price: 399,
    image: '/images/products/t-shirts/berolei-khorcha/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/berolei-khorcha/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/berolei-khorcha/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/berolei-khorcha/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/berolei-khorcha/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/berolei-khorcha/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/berolei-khorcha/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/berolei-khorcha/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Hoche Bhojon Barche Ojon',
    price: 399,
    image: '/images/products/t-shirts/hoche-bhojon-barche-ojon/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/hoche-bhojon-barche-ojon/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/hoche-bhojon-barche-ojon/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/hoche-bhojon-barche-ojon/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/hoche-bhojon-barche-ojon/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/hoche-bhojon-barche-ojon/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Green',         image: '/images/products/t-shirts/hoche-bhojon-barche-ojon/green.jpeg'         },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/hoche-bhojon-barche-ojon/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Savage',
    price: 399,
    image: '/images/products/t-shirts/savage/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/savage/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/savage/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/savage/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/savage/black.jpeg'         },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/savage/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/savage/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Jibone Prochur Chap',
    price: 399,
    image: '/images/products/t-shirts/jibone-prochur-chap/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/jibone-prochur-chap/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/jibone-prochur-chap/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/jibone-prochur-chap/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/jibone-prochur-chap/black.jpeg'         },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/jibone-prochur-chap/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/jibone-prochur-chap/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Feluda',
    price: 399,
    image: '/images/products/t-shirts/feluda/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/feluda/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/feluda/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/feluda/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/feluda/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/feluda/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/feluda/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/feluda/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Kolkata Ache Kolkata Tei',
    price: 399,
    image: '/images/products/t-shirts/kolkata-ache-kolkata-tei/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/kolkata-ache-kolkata-tei/vibrant-red.jpeg'   },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/kolkata-ache-kolkata-tei/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/kolkata-ache-kolkata-tei/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/kolkata-ache-kolkata-tei/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/kolkata-ache-kolkata-tei/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/kolkata-ache-kolkata-tei/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Taranth Tantrik',
    price: 399,
    image: '/images/products/t-shirts/taranth-tantrik/black.jpeg',
    colors: [
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/taranth-tantrik/black.jpeg'         },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/taranth-tantrik/white.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/taranth-tantrik/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/taranth-tantrik/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/taranth-tantrik/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Khuror Kol',
    price: 399,
    image: '/images/products/t-shirts/khuror-kol/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/khuror-kol/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/khuror-kol/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/khuror-kol/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/khuror-kol/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/khuror-kol/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/khuror-kol/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/khuror-kol/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Pyancha Pyanchani',
    price: 399,
    image: '/images/products/t-shirts/pyancha-pyanchani/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/pyancha-pyanchani/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/pyancha-pyanchani/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/pyancha-pyanchani/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/pyancha-pyanchani/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/pyancha-pyanchani/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/pyancha-pyanchani/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/pyancha-pyanchani/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Bosonto Ese Geche',
    price: 399,
    image: '/images/products/t-shirts/bosonto-ese-geche/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/bosonto-ese-geche/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/bosonto-ese-geche/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/bosonto-ese-geche/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/bosonto-ese-geche/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/bosonto-ese-geche/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/bosonto-ese-geche/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/bosonto-ese-geche/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Music',
    price: 399,
    image: '/images/products/t-shirts/music/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/music/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/music/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/music/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/music/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/music/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/music/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/music/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Highly Suspicious',
    price: 399,
    image: '/images/products/t-shirts/highly-suspicious/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/highly-suspicious/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/highly-suspicious/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/highly-suspicious/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/highly-suspicious/black.jpeg'         },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/highly-suspicious/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/highly-suspicious/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Kaje Allergy Arame Energy',
    price: 399,
    image: '/images/products/t-shirts/kaje-allergy-arame-energy/white.jpeg',
    colors: [
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/kaje-allergy-arame-energy/white.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/kaje-allergy-arame-energy/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/kaje-allergy-arame-energy/olive-green.jpeg'   },
    ],
  },
  {
    name: 'Oot Ki Kanta Bechhe Khay',
    price: 399,
    image: '/images/products/t-shirts/oot-ki-kanta-bechhe-khay/black.jpeg',
    colors: [
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/oot-ki-kanta-bechhe-khay/black.jpeg'         },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/oot-ki-kanta-bechhe-khay/white.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/oot-ki-kanta-bechhe-khay/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/oot-ki-kanta-bechhe-khay/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/oot-ki-kanta-bechhe-khay/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Ami Sate Panche Nei',
    price: 399,
    image: '/images/products/t-shirts/ami-sate-panche-nei/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/ami-sate-panche-nei/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/ami-sate-panche-nei/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/ami-sate-panche-nei/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/ami-sate-panche-nei/black.jpeg'         },
      { hex: '#feee29', name: 'Bright Yellow', image: '/images/products/t-shirts/ami-sate-panche-nei/bright-yellow.jpeg' },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/ami-sate-panche-nei/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/ami-sate-panche-nei/metallic-blue.jpeg' },
    ],
  },
  {
    name: 'Kaoke Tel Marina',
    price: 399,
    image: '/images/products/t-shirts/kaoke-tel-marina/vibrant-red.jpeg',
    colors: [
      { hex: '#d22334', name: 'Vibrant Red',   image: '/images/products/t-shirts/kaoke-tel-marina/vibrant-red.jpeg'   },
      { hex: '#f3f3f3', name: 'White',         image: '/images/products/t-shirts/kaoke-tel-marina/white.jpeg'         },
      { hex: '#54575c', name: 'Grey',          image: '/images/products/t-shirts/kaoke-tel-marina/grey.jpeg'          },
      { hex: '#2b2b2b', name: 'Black',         image: '/images/products/t-shirts/kaoke-tel-marina/black.jpeg'         },
      { hex: '#384b38', name: 'Olive Green',   image: '/images/products/t-shirts/kaoke-tel-marina/olive-green.jpeg'   },
      { hex: '#202157', name: 'Metallic Blue', image: '/images/products/t-shirts/kaoke-tel-marina/metallic-blue.jpeg' },
    ],
  },
];

export default tShirt;
